# Build the app image
FROM python:3.10

# Create directory for the app user
RUN mkdir -p /home/app

# Create the app user
RUN groupadd app && useradd -g app app

# Create the home directory
ENV APP_HOME=/home/app/api
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# install
COPY . $APP_HOME
RUN pip install -r requirements-dev.txt
RUN pip install -e .

# Ensure the entrypoint script has execution permissions
RUN chmod +x $APP_HOME/entrypoint.sh

RUN chown -R app:app $APP_HOME
USER app

# Provide the absolute path to the entrypoint script
CMD ["/home/app/api/entrypoint.sh"]

