"""fix field user_id

Revision ID: 503140aebd47
Revises: b2b7178cbfa1
Create Date: 2025-05-14 14:24:45.078335

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '503140aebd47'
down_revision: Union[str, None] = 'b2b7178cbfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_userid', 'like', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_userid', 'like', type_='unique')
    # ### end Alembic commands ###
