"""alter_field_user_id

Revision ID: 6b7d526e9199
Revises: 503140aebd47
Create Date: 2025-05-16 15:19:18.617838

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b7d526e9199'
down_revision: Union[str, None] = '503140aebd47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_userid', 'like', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_userid', 'like', ['user_id'])
    # ### end Alembic commands ###
